<a href="https://colab.research.google.com/github/harshbhadoriya456-source/Data_Analysis_Colab/blob/main/Data_Loading_%26_Storage.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**DATA LOADING & STORAGE**

DATA SOURCE -> DATA LOAD ->  PANDAS DATAFRAME -> DATA INSPECTION -> DATA STORAGE

In [2]:
import pandas as pd

In [7]:
import os
print("Current dir")
print(os.getcwd())

Current dir
/content

In [9]:
print(os.listdir())

['.config', 'Dataset of Diabetes .csv', 'sample_data']

In [45]:
with open("student.csv", "w") as f:
    f.write("Name,Marks\n")
    f.write("Harsh,90\n")


with open("student.csv", "r") as f:
    data = f.read()

df = pd.read_csv("student.csv")

df.to_json("student.json")
print(pd.read_json("student.json"))

df.to_excel("student.xlsx")
print(pd.read_excel("student.xlsx"))

df.to_xml("student.xml")
print(pd.read_xml("student.xml"))

    Name  Marks
0  Harsh     90
   Unnamed: 0   Name  Marks
0           0  Harsh     90
   index   Name  Marks
0      0  Harsh     90

In [26]:
print("Shape:")
print(df.shape)
print("\nColumns:")
print(df.columns)
print("\nInfo:")
print(df.info)
print("\nData Types:")
print(df.dtypes)

Shape:
(1, 2)

Columns:
Index(['Name', 'Marks'], dtype='object')

Info:
<bound method DataFrame.info of     Name  Marks
0  Harsh     90>

Data Types:
Name     object
Marks     int64
dtype: object

In [35]:
print("Separator change:")
df_csv=pd.read_csv("student.csv", sep="|")
df_csv

Separator change:

  Name,Marks
0   Harsh,90

In [55]:
#assign header and checking what happens after making header=NULL
df_csv=pd.read_csv("student.csv", header=None)
df_csv

     0      1      2       3
0   ID   Name  Marks  Branch
1  101  Harsh     90     CSE
2  102   Aman     85     ECE
3  103  Rahul     88     CSE
4  104  Priya     95      IT
5  105  Rohan     80      ME

In [50]:
with open("student.csv", "w") as f:
    f.write("ID,Name,Marks,Branch\n")
    f.write("101,Harsh,90,CSE\n")
    f.write("102,Aman,85,ECE\n")
    f.write("103,Rahul,88,CSE\n")
    f.write("104,Priya,95,IT\n")
    f.write("105,Rohan,80,ME\n")


df1 = pd.read_csv("student.csv",
                  names=["ID", "Student", "Score", "Department"],
                  header=0)
print("NAMES:")
print(df1)

NAMES:
    ID Student  Score Department
0  101   Harsh     90        CSE
1  102    Aman     85        ECE
2  103   Rahul     88        CSE
3  104   Priya     95         IT
4  105   Rohan     80         ME

In [52]:
df2 = pd.read_csv("student.csv", index_col="ID")
print("\nINDEX_COL:")
print(df2)

INDEX_COL:
      Name  Marks Branch
ID
101  Harsh     90    CSE
102   Aman     85    ECE
103  Rahul     88    CSE
104  Priya     95     IT
105  Rohan     80     ME

In [58]:
df3=pd.read_csv("student.csv",usecols=["Name"])
print("\nUSECOLS:")
print(df3)

USECOLS:
    Name
0  Harsh
1   Aman
2  Rahul
3  Priya
4  Rohan

In [61]:
df4=pd.read_csv("student.csv", nrows=2)
print("\nNROWS:")
print(df4)

NROWS:
    ID   Name  Marks Branch
0  101  Harsh     90    CSE
1  102   Aman     85    ECE

In [64]:
df5=pd.read_csv("student.csv", skiprows=2)
print("\nSKIPROWS:")
print(df5)

SKIPROWS:
   102   Aman  85  ECE
0  103  Rahul  88  CSE
1  104  Priya  95   IT
2  105  Rohan  80   ME